// ── Molecule Lookup: recognised components ─────────────────────────────
// Split out of index.html so the vendored table and our additions are each
// a file you can diff against its source (user decision 2026-08-17).
//
// Loaded as a sibling <script>, NOT fetched. The page's Offline mode means
// "ask no third-party service", and a same-origin script that ships with the
// page is available exactly whenever the page is — so nothing about offline
// operation changes by moving these out.

// Known non-active components — VENDORED, not hand-written. Membership, not
// size, is what marks a fragment as NOT the drug (see the pamoate note above),
// so this table is load-bearing for correctness and its provenance matters.
//
// Source: ChEMBL_Structure_Pipeline `salts.smi` + `solvents.smi`
// (github.com/chembl/ChEMBL_Structure_Pipeline), MIT licensed,
// Copyright (c) 2019 Greg Landrum. An earlier version of this table was
// written from memory and silently omitted camsylate, esylate, methylsulfate,
// teoclate, lactobionate and ~15 others — which is why it now comes from a
// maintained list rather than being assembled by hand.
//
// Inlined rather than fetched: Offline mode has to keep working, and a
// request for the vocabulary would be the one thing that couldn't.
//
// Two deliberate departures from the source file:
//  1. `Maleate and Fumarate` is ONE entry there — their pipeline strips salts
//     by substructure match, which ignores stereochemistry, so the distinction
//     doesn't matter to them. It matters here: maleate's cis C=C is what
//     attacked amlodipine's primary amine, fumarate's trans one is inert.
//     Split into stereo-specific Maleate and Fumarate, keeping their
//     stereo-free original as Butenedioate so a record that doesn't specify
//     geometry still resolves.
//  2. Nothing is ADDED. Co-crystal formers (nicotinamide, urea, proline) are
//     absent from a SALTS list and are left absent, so they bold — the tool
//     declines to assert a component is inert on my say-so. Procaine is
//     likewise absent and bolds, which is arguably right: it is a local
//     anaesthetic doing real work in procaine benzylpenicillin, not merely a
//     depot-forming counterion.
//
// Entries are [name, type, SMILES]. SMILES rather than InChIKeys, so the keys
// are derived below by the SAME RDKit that matches them and cannot drift.
var VOCAB = [
  ["Tetrafluoroboranuide", "counterion", "F[B-](F)(F)F"],
  ["Arginine", "counterion", "NC(CCCNC(=N)N)C(=O)O"],
  ["Deanol", "counterion", "CN(C)CCO"],
  ["2-(Diethylamino)ethanol", "counterion", "CCN(CC)CCO"],
  ["Ethanolamine", "counterion", "NCCO"],
  ["DiMeglumine", "counterion", "CNCC(O)C(O)C(O)C(O)CO"],
  ["Acetate", "counterion", "CC(=O)O"],
  ["Aceturate", "counterion", "CC(=O)NCC(=O)O"],
  ["Stearate", "counterion", "CCCCCCCCCCCCCCCCCC(=O)O"],
  ["Adipate", "counterion", "OC(=O)CCCCC(=O)O"],
  ["Aluminium", "counterion", "[Al]"],
  ["Ammonium", "counterion", "N"],
  ["Ascorbate", "counterion", "OCC(O)C1OC(=O)C(=C1O)O"],
  ["Aspartate", "counterion", "NC(CC(=O)O)C(=O)O"],
  ["Barium", "counterion", "[Ba]"],
  ["Benethamine", "counterion", "C(Cc1ccccc1)NCc2ccccc2"],
  ["Benzathine", "counterion", "C(CNCc1ccccc1)NCc2ccccc2"],
  ["Benzoate", "counterion", "OC(=O)c1ccccc1"],
  ["Besylate", "counterion", "OS(=O)(=O)c1ccccc1"],
  ["Bismuth", "counterion", "[Bi]"],
  ["Bromide", "counterion", "Br"],
  ["Butyraldehyde", "counterion", "CCCC=O"],
  ["Ethyl Butanoate", "counterion", "CCCC(=O)OCC"],
  ["Calcium", "counterion", "[Ca]"],
  ["Camsylate", "counterion", "CC1(C)C2CCC1(CS(=O)(=O)O)C(=O)C2"],
  ["Carbonate", "counterion", "OC(=O)O"],
  ["Chloride", "counterion", "Cl"],
  ["Choline", "counterion", "C[N+](C)(C)CCO"],
  ["Citrate", "counterion", "OC(=O)CC(O)(CC(=O)O)C(=O)O"],
  ["Closylate", "counterion", "OS(=O)(=O)c1ccc(Cl)cc1"],
  ["Cyclamate", "counterion", "OS(=O)(=O)NC1CCCCC1"],
  ["Dichloroacetate", "counterion", "OC(=O)C(Cl)Cl"],
  ["Diethylamine", "counterion", "CCNCC"],
  ["Dimethylethanolamine", "counterion", "CC(C)(N)CO"],
  ["Diolamine", "counterion", "OCCNCCO"],
  ["Edamine", "counterion", "NCCN"],
  ["Edisylate", "counterion", "OS(=O)(=O)CCS(=O)(=O)O"],
  ["Epolamine", "counterion", "OCCN1CCCC1"],
  ["Erbumine", "counterion", "CC(C)(C)N"],
  ["Estolate", "counterion", "CCCCCCCCCCCCOS(=O)(=O)O"],
  ["Esylate", "counterion", "CCS(=O)(=O)O"],
  ["Ethylsulfate", "counterion", "CCOS(=O)(=O)O"],
  ["Fluoride", "counterion", "F"],
  ["Formate", "counterion", "OC=O"],
  ["Gluceptate", "counterion", "OCC(O)C(O)C(O)C(O)C(O)C(=O)O"],
  ["Gluconate", "counterion", "OCC(O)C(O)C(O)C(O)C(=O)O"],
  ["Glucuronate", "counterion", "OC1OC(C(O)C(O)C1O)C(=O)O"],
  ["Glutamate", "counterion", "NC(CCC(=O)O)C(=O)O"],
  ["Glycerate", "counterion", "OCC(O)CO"],
  ["Glycerophosphate", "counterion", "OCC(O)COP(=O)(O)O"],
  ["Hexafluorophosphate", "counterion", "F[P](F)(F)(F)(F)F"],
  ["Hypophosphite", "counterion", "OP=O"],
  ["Iodide", "counterion", "I"],
  ["Isethionate", "counterion", "OCCS(=O)(=O)O"],
  ["Potassium", "counterion", "[K]"],
  ["Lactate", "counterion", "CC(O)C(=O)O"],
  ["Lactobionate", "counterion", "OCC(O)C(OC1OC(CO)C(O)C(O)C1O)C(O)C(O)C(=O)O"],
  ["Lithium", "counterion", "[Li]"],
  ["Lysine", "counterion", "NCCCCC(N)C(=O)O"],
  ["Malate", "counterion", "OC(CC(=O)O)C(=O)O"],
  ["Maleate", "counterion", "OC(=O)/C=C\\C(=O)O"],
  ["Fumarate", "counterion", "OC(=O)/C=C/C(=O)O"],
  ["Butenedioate", "counterion", "OC(=O)C=CC(=O)O"],
  ["Mesylate", "counterion", "CS(=O)(=O)O"],
  ["Metaphosphate", "counterion", "OP(=O)=O"],
  ["Methosulfate", "counterion", "COS(=O)(=O)O"],
  ["Magnesium", "counterion", "[Mg]"],
  ["Monofluorophosphate", "counterion", "OP(=O)(O)F"],
  ["Sodium", "counterion", "[Na]"],
  ["Napadisilate", "counterion", "OS(=O)(=O)c1cccc2c(cccc12)S(=O)(=O)O"],
  ["Napsylate", "counterion", "OS(=O)(=O)c1ccc2ccccc2c1"],
  ["Nitrate", "counterion", "O[N](=O)O"],
  ["Oxalate", "counterion", "OC(=O)C(=O)O"],
  ["Palmitate", "counterion", "CCCCCCCCCCCCCCCC(=O)O"],
  ["Pamoate", "counterion", "OC(=O)c1cc2ccccc2c(Cc3c(O)c(cc4ccccc34)C(=O)O)c1O"],
  ["Perchlorate", "counterion", "OCl(=O)(=O)=O"],
  ["Phosphanilate", "counterion", "Nc1ccc(cc1)P(=O)(O)O"],
  ["Phosphate", "counterion", "OP(=O)(O)O"],
  ["Picrate", "counterion", "Oc1c(cc(cc1[N+](=O)[O-])[N+](=O)[O-])[N+](=O)[O-]"],
  ["Piperazine", "counterion", "C1CNCCN1"],
  ["Propylene Glycol", "counterion", "CC(O)CO"],
  ["Saccharin", "counterion", "O=C1NS(=O)(=O)c2ccccc12"],
  ["Salicylate", "counterion", "OC(=O)c1ccccc1O"],
  ["Silver", "counterion", "[Ag]"],
  ["Strontium", "counterion", "[Sr]"],
  ["Succinate", "counterion", "OC(=O)CCC(=O)O"],
  ["Sulfate", "counterion", "OS(=O)(=O)O"],
  ["Sulfosalicylate", "counterion", "OC(=O)c1cccc(c1O)S(=O)(=O)O"],
  ["Sulphide", "counterion", "[S-2]"],
  ["Terephthalate", "counterion", "OC(=O)c1ccc(cc1)C(=O)O"],
  ["Tosylate", "counterion", "Cc1ccc(cc1)S(=O)(=O)O"],
  ["Triclofenate", "counterion", "Oc1cc(Cl)c(Cl)cc1Cl"],
  ["Triethylamine", "counterion", "CCN(CC)CC"],
  ["Trifenatate", "counterion", "OC(=O)C(c1ccccc1)(c2ccccc2)c3ccccc3"],
  ["Triflutate", "counterion", "OC(=O)C(F)(F)F"],
  ["Tromethamine", "counterion", "NC(CO)(CO)CO"],
  ["Buciclate", "counterion", "CCCCC1CCC(CC1)C(=O)O"],
  ["Butyrate", "counterion", "CCCC(=O)O"],
  ["Caproate", "counterion", "CCCCCC(=O)O"],
  ["Cyclotate", "counterion", "CC12CCC(CC1)(C=C2)C(=O)O"],
  ["Cypionate", "counterion", "OC(=O)CCC1CCCC1"],
  ["Daproate", "counterion", "CN(C)CCC(=O)O"],
  ["EDTA", "counterion", "OC(=O)CN(CCN(CC(=O)O)CC(=O)O)CC(=O)O"],
  ["Elaidate and oleate", "counterion", "CCCCCCCCC=CCCCCCCCC(=O)O"],
  ["Enanthate", "counterion", "CCCCCCC(=O)O"],
  ["Etabonate", "counterion", "CCOC(=O)O"],
  ["Ethanediol", "counterion", "COCCO"],
  ["Etiprate", "counterion", "OC(=O)CNC(=O)c1ccccc1"],
  ["Etzadroxil", "counterion", "CCC(CC)C(=O)OCO"],
  ["Fostedate", "counterion", "CCCCCCCCCCCCCCOP(=O)(O)O"],
  ["Furoate", "counterion", "OC(=O)c1occc1"],
  ["Hybenzate", "counterion", "OC(=O)c1ccccc1C(=O)c2ccc(O)cc2"],
  ["Laurate", "counterion", "CCCCCCCCCCCC(=O)O"],
  ["Mebutate", "counterion", "CC=C(C)C(=O)O"],
  ["Mepesuccinate", "counterion", "COC(=O)CC(O)(CCCC(C)(C)O)C(=O)O"],
  ["Metazoate", "counterion", "OC(=O)c1cccc(c1)S(=O)(=O)O"],
  ["Methionil", "counterion", "CSCCC(N)C(=O)C"],
  ["Nicotinate", "counterion", "OC(=O)c1cccnc1"],
  ["Peroxide", "counterion", "OO"],
  ["Phenpropionate", "counterion", "OC(=O)CCc1ccccc1"],
  ["Phenylacetate", "counterion", "OC(=O)Cc1ccccc1"],
  ["Pivalate", "counterion", "CC(C)(C)C(=O)O"],
  ["Propionate", "counterion", "CCC(=O)O"],
  ["Tebutate", "counterion", "CC(C)(C)CC(=O)O"],
  ["Trolamine", "counterion", "OCCN(CCO)CCO"],
  ["Undecylate", "counterion", "CCCCCCCCCCC(=O)O"],
  ["Undecylenate", "counterion", "OC(=O)CCCCCCCCC=C"],
  ["Valerate", "counterion", "CCCCC(=O)O"],
  ["Water", "counterion", "O"],
  ["Xinafoate", "counterion", "OC(=O)c1ccc2ccccc2c1O"],
  ["Zinc", "counterion", "[Zn]"],
  ["Imidazole", "counterion", "c1c[nH]cn1"],
  ["4-(2-Hydroxyethyl)morpholine", "counterion", "OCCN1CCOCC1"],
  ["4-Acetamidobenzoic acid", "counterion", "CC(=O)Nc1ccc(cc1)C(=O)O"],
  ["Camphoric acid", "counterion", "CC1(C)C(CCC1(C)C(=O)O)C(=O)O"],
  ["Capric acid", "counterion", "CCCCCCCCCC(=O)O"],
  ["Caprylic acid", "counterion", "CCCCCCCC(=O)O"],
  ["Cinnamic acid", "counterion", "OC(=O)C=Cc1ccccc1"],
  ["Mucic acid", "counterion", "OC(C(O)C(O)C(=O)O)C(O)C(=O)O"],
  ["Gentisic acid", "counterion", "OC(=O)c1cc(O)ccc1O"],
  ["Glutaric acid", "counterion", "OC(=O)CCCC(=O)O"],
  ["2-Oxoglutaric acid", "counterion", "OC(=O)CCC(=O)C(=O)O"],
  ["Glycolic acid", "counterion", "OCC(=O)O"],
  ["Isobutyric acid", "counterion", "CC(C)C(=O)O"],
  ["Mandelic acid", "counterion", "OC(C(=O)O)c1ccccc1"],
  ["Orotic acid", "counterion", "OC(=O)c1cc(=O)nc(=O)n1"],
  ["Pyroglutamic acid", "counterion", "OC(=O)C1CCC(=O)N1"],
  ["Tartrate", "counterion", "OC(C(O)C(=O)O)C(=O)O"],
  ["Thiocyanic acid", "counterion", "SC#N"],
  ["Methyl Iodide", "counterion", "CI"],
  ["Sulfurous Acid", "counterion", "OS(=O)O"],
  ["Dicyclohexylamine", "counterion", "C1CCC(CC1)NC2CCCCC2"],
  ["Triflate", "counterion", "OS(=O)(=O)C(F)(F)F"],
  ["Mesitylene sulfonate", "counterion", "Cc1cc(C)c(c(C)c1)S(=O)(=O)O"],
  ["Malonic acid", "counterion", "OC(=O)CC(=O)O"],
  ["Fluorosulfuric acid", "counterion", "OS(=O)(=O)F"],
  ["Acetylsulfate", "counterion", "CC(=O)OS(=O)(=O)O"],
  ["Proton", "counterion", "[H]"],
  ["Rubidium", "counterion", "[Rb]"],
  ["Cesium", "counterion", "[Cs]"],
  ["Francium", "counterion", "[Fr]"],
  ["Beryllium", "counterion", "[Be]"],
  ["Radium", "counterion", "[Ra]"],
  ["Glucuronate open form", "counterion", "C(=O)C(O)C(O)C(O)C(O)C(=O)O"],
  ["Dimepranol", "counterion", "CC(O)CN(C)C"],
  ["WATER", "solvent", "[OH2]"],
  ["DICHLOROMETHANE", "solvent", "ClCCl"],
  ["TRICHLOROMETHANE", "solvent", "ClC(Cl)Cl"],
  ["ETHYL ACETATE", "solvent", "CCOC(=O)C"],
  ["METHANOL", "solvent", "CO"],
  ["PROPAN-2-OL", "solvent", "CC(C)O"],
  ["ACETONE", "solvent", "CC(=O)C"],
  ["DMSO", "solvent", "CS(=O)C"],
  ["ETHANOL", "solvent", "CCO"],
];
